spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/laozi?useUnicode=true&characterEncoding=utf-8
#    url: jdbc:mysql://localhost:3306/laozi
    username: root
    password: 123456
#    password: 981218

  thymeleaf:
    cache: false